# Generated by Django 3.0.3 on 2020-07-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20200701_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertodoitem',
            name='priority',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customertodoitem',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
