# Generated by Django 3.0.3 on 2020-07-02 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20200702_2227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
